name:    yesod-bug1487
version: "0.0.0"

dependencies:
- base
- template-haskell
- directory
- text
- bytestring
- containers
- parsec

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
